image: alpine/edge
packages:
  - rust
  - cargo
  - alsa-lib
sources:
  - https://git.sr.ht/~shockham/meshi
tasks:
  - build: |
      cd meshi
      cargo build
  - test: |
      cd meshi
      cargo test
